### ISSUE TITLE
Mattermost: Enterprise installation hangs forever and never completes

### ISSUE THREAD

**Issue by conneryn** [c6o/provisioners#109]
### Summary:
Tried a fresh installation of Mattermost **enterprise** edition, but it does not finish installing (2+ hours so far).

NOTE: I did not supply a "mattermost license secret", though it says it's optional.

### Observed Results:
A clear and concise description of what happened that was not expected.

### Screenshots:
![image](https://user-images.githubusercontent.com/4723264/100947945-95b30c00-34bb-11eb-9add-330ecd1192ea.png)

### Failure Logs
Please include any relevant log snippets or files here.

## Checklist
- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ ] I have provided sufficient information for the team

**Comment by conneryn** [comment]
Tried and confirmed that preview version does work as expected.

**Comment by nothingmn** [comment]
Installing enterprise edition:

Back-off restarting failed container

Error: failed to start container "mattermost-operator": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"mattermost-operator\": executable file not found in $PATH": unknown

**Comment by Canuckaholic** [comment]
This needs to be re-tested.
