### ISSUE TITLE
Adminer installs but does not run.

### ISSUE THREAD

**Issue by robblovell** [c6o/provisioners#143]
### Summary:

On develop
Install Adminer into your cloud
after install, run it
Result: "Failed to load resource: the server responded with a status of 503 ()"

I deleted the app and reinstalled and it worked.

It is possible there is something around first time cloud install after a deployment.

## Checklist
- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ ] I have provided sufficient information for the team

**Comment by nothingmn** [comment]
Determined this was due to an OS level issue, which has been fixed
