### ISSUE TITLE
Six apps manifests need to be re-published

### ISSUE THREAD

**Issue by robblovell** [c6o/provisioners#145]
### Background:

There are five app manifests on staging (and possibly production) that aren't published via ```yarn publish-manifests```.  These are: 

- [ ] Akaunting
- [ ] MediaWiki
- [ ] Mibew
- [ ] vTiger CRM
- [ ] Wallabag
- [ ] Zimbra

The reason for the republish is so that they get their "cost" flag set to free, paid, or both, depending on how their editions have prices. Re-publishing will set them accordingly. Probably, they are all 'free', so their records could be edited directly to add a ```"cost": "free"``` to their records.

Example from Echo Server:
```
{
    "_id" : "01ERDKZ8DS3197DG2JRF61NVWZ",
    "name" : "Echo Server",
    "package" : "@provisioner/appengine",
    "description" : "Ever want to meet an server that is a good listener? Look no further, connect with your inner narcissist and buy echo server today!",
    "summary" : "Echo server just replies back what you sent it.",
    "category" : "dev-tools",
    "keywords" : [ 
        "Developer", 
        "Tools"
    ],
    "repo" : "https://github.com/robblovell/echo-server",
    "license" : "https://www.apache.org/licenses/LICENSE-2.0.html",
    "support" : "https://github.com/robblovell/echo-server/issues",
    "provisioner" : {
        "repo" : "https://github.com/robblovell/echo-server",
        "support" : "https://github.com/robblovell/echo-server/issues"
    },
    "namespace" : "echoserver",
    "cost" : "both",
    "updatedOn" : ISODate("2020-12-23T05:51:25.362Z")
}
```

**Comment by nothingmn** [comment]
All of these were deprecated / removed out of source.  Typically they had unmet dependencies which we could satisfy in the short term.
