### ISSUE TITLE
Solid Server icon broken

### ISSUE THREAD

**Issue by robblovell** [c6o/provisioners#148]
### Summary:
Connery's solid server app has a broken icon on production.

## Checklist
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have provided sufficient information for the team

**Comment by conneryn** [comment]
Oops, sorry, not sure how it became public, switched back to private.   Though brings up an interesting point that maybe we will eventually want a minimum set of required fields before they can be published publicly.
