### ISSUE TITLE
Assign apps to Marketplace categories

### ISSUE THREAD

**Issue by H4GG15** [c6o/provisioners#57]
### Assign the following apps to the associated marketplace categories:
 Grafana - Monitoring
 Node-RED - IoT
 Visual Studio Code - Developer Tools
 Prometheus - Monitoring
 Grafana - Monitoring | Dashboards
 Precog - ETL
 Logging (ELK) - Logging (note: can we also change the app name for consistency?)
 Verdaccio - Developer Tools
 Certificate Manager - DevOps tools (note: is there a more specific app name we can use?)

**Comment by nothingmn** [comment]
This has been completed, along with the new manifest changes.
